#!/usr/bin/env python
from main import ARGO, SST, SLA, Hovmoller, Anomaly, TS, Timeseries, Decimate, MVR, MLD

# -------------------------  INITIALIZING METHODS   -------------------------
print ('Initializing Job')
argo = ARGO()
sst = SST()
sla = SLA()
hovmoller = Hovmoller()
anomaly = Anomaly()
TS_diagram = TS()
timeseries = Timeseries()
mvr = MVR()
mld = MLD()
dec=Decimate()
#-------------------------  PLEASE SELECT YOUR TASKS   -------------------------
#                   All the following modules are available

argo.profiles()
argo.errorEvolution()
sst.compute()
sla.compute()
hovmoller.compute()
anomaly.hovmoller()
anomaly.timeseries()
anomaly.maps()
TS_diagram.dailyPointProfile(31,41.5) # TS diagram in a point (x,y)
TS_diagram.yearlyMean()
TS_diagram.monthlyMean() # to be tested
timeseries.argo()
timeseries.argo2exps()
timeseries.depthBins()
timeseries.salinityVol()
timeseries.domainAverage()
mld.compute()
mvr.compute()
dec.compute(10) # Reduce resolution. N is the decimation factor



#-------------------------  PLOTS   -------------------------
# you can also add title anc stats(...,statistics=False,suptitle=False)


